local filetypes = {};

filetypes.entries = {
	---+${class}
	["default"]                 = { name = nil,                    icon = "󰻺 ", hl = 1 },
	["nosyntax"]                = { name = "Unknown",              icon = "󰡯 ", hl = 1 },

	["abaqus"]                  = { name = "Abaqus",               icon = "󱛠 ", hl = 3 },
	["amiga"]                   = { name = "Amiga",                icon = "󰹀 ", hl = 4 },
	["asm"]                     = { name = "Assembly",             icon = " ", hl = 6 },
	["aspperl"]                 = { name = "ASP+Perl",             icon = " ", hl = 1 },
	["aspvbs"]                  = { name = "ASP+VBScript",         icon = " ", hl = 1 },
	["awk"]                     = { name = "AWK",                  icon = " ", hl = 2 },
	["baan"]                    = { name = "BaaN",                 icon = "󰯂 ", hl = 7 },
	["bash"]                    = { name = "Bash",                 icon = " ", hl = 5 },
	["basic"]                   = { name = "BASIC",                icon = "󰯁 ", hl = 1 },
	["bat"]                     = { name = "Bat",                  icon = "󰭟 ", hl = 1 },
	["bc"]                      = { name = "Basic Calculator",     icon = "󰪚 ", hl = 1 },
	["bindzone"]                = { name = "BIND Zone",            icon = "󰲝 ", hl = 1 },
	["bitbake"]                 = { name = "BitBake",              icon = " ", hl = 1 },
	["c"]                       = { name = "C",                    icon = " ", hl = 6 },
	["cfengine"]                = { name = "CFEngine",             icon = " ", hl = 5 },
	["cfg"]                     = { name = "Configuration",        icon = " ", hl = 7 },
	["ch"]                      = { name = "Change",               icon = " ", hl = 7 },
	["change"]                  = { name = "Change",               icon = " ", hl = 7 },
	["changelog"]               = { name = "Changelog",            icon = " ", hl = 4 },
	["chill"]                   = { name = "CHILL",                icon = "󰼪 ", hl = 7 },
	["cl"]                      = { name = "OpenCL",               icon = " ", hl = 1 },
	["clipper"]                 = { name = "Clipper",              icon = "󰯂 ", hl = 7 },
	["clojure"]                 = { name = "Clojure",              icon = " ", hl = 7 },
	["conf"]                    = { name = "Configuration",        icon = " ", hl = 5 },
	["context"]                 = { name = "Context",              icon = "󰯂 ", hl = 7 },
	["coq"]                     = { name = "Coq",                  icon = "󰯂 ", hl = 7 },
	["cpp"]                     = { name = "C++",                  icon = " ", hl = 6 },
	["crystal"]                 = { name = "Crystal",              icon = " ", hl = 1 },
	["csh"]                     = { name = "C Shell",              icon = " ", hl = 4 },
	["cvs"]                     = { name = "CVS commit",           icon = " ", hl = 4 },
	["cweb"]                    = { name = "CWEB",                 icon = "󰎞 ", hl = 1 },
	["cynlib"]                  = { name = "CynLib",               icon = "󰯂 ", hl = 7 },
	["d"]                       = { name = "D",                    icon = " ", hl = 7 },
	["dart"]                    = { name = "Dart",                 icon = " ", hl = 7 },
	["debchangelog"]            = { name = "DebChangelog",         icon = " ", hl = 2 },
	["debcontrol"]              = { name = "DebControl",           icon = " ", hl = 2 },
	["debcopyright"]            = { name = "DebCopyright",         icon = " ", hl = 2 },
	["def"]                     = { name = "Module-definition",    icon = "󰍲 ", hl = 1 },
	["diff"]                    = { name = "Diff",                 icon = " ", hl = 3 },
	["diva"]                    = { name = "Diva",                 icon = "󰯂 ", hl = 7 },
	["dtd"]                     = { name = "Type Definition",      icon = "󱪗 ", hl = 1 },
	["dtrace"]                  = { name = "DTrace",               icon = "󰯂 ", hl = 7 },
	["edif"]                    = { name = "EDIF",                 icon = "󰯂 ", hl = 7 },
	["eiffel"]                  = { name = "Eiffel",               icon = "󱕫 ", hl = 7 },
	["elixir"]                  = { name = "Elixir",               icon = " ", hl = 1 },
	["erlang"]                  = { name = "Erlang",               icon = " ", hl = 1 },
	["euphoria4"]               = { name = "Euphoria4",            icon = "󰯂 ", hl = 7 },
	["execline"]                = { name = "Execline",             icon = " ", hl = 3 },
	["expect"]                  = { name = "Expect",               icon = "󰯂 ", hl = 7 },
	["faust"]                   = { name = "Faust",                icon = " ", hl = 1 },
	["fdcc"]                    = { name = "FDCC",                 icon = "󰯂 ", hl = 7 },
	["fennel"]                  = { name = "Fennel",               icon = " ", hl = 7 },
	["fish"]                    = { name = "FISH",                 icon = "󰻳 ", hl = 5 },
	["foam"]                    = { name = "FoamFile",             icon = "󰯂 ", hl = 7 },
	["form"]                    = { name = "Form",                 icon = "󰔃 ", hl = 7 },
	["forth"]                   = { name = "Forth",                icon = "󰯂 ", hl = 7 },
	["fortran"]                 = { name = "Fortran",              icon = " ", hl = 7 },
	["freebasic"]               = { name = "Free BASIC",           icon = "󰯂 ", hl = 7 },
	["fsharp"]                  = { name = "F#",                   icon = " ", hl = 6 },
	["fvwm"]                    = { name = "FVWM",                 icon = "󱚣 ", hl = 2 },
	["fvwm3m5"]                 = { name = "FVWM",                 icon = "󱚣 ", hl = 2 },
	["git"]                     = { name = "Git",                  icon = " ", hl = 3 },
	["gitsendemail"]            = { name = "Git-send-mail",        icon = "󰺻 ", hl = 3 },
	["gnuplot"]                 = { name = "GNUPlot",              icon = "󰙭 ", hl = 7 },
	["go"]                      = { name = "Golang",               icon = " ", hl = 6 },
	["godoc"]                   = { name = "Godoc",                icon = "󰟓 ", hl = 6 },
	["gomod"]                   = { name = "Gomod",                icon = "󰏖 ", hl = 6 },
	["gprof"]                   = { name = "Gprof",                icon = "󰓅 ", hl = 7 },
	["groovy"]                  = { name = "Groovy",               icon = " ", hl = 1 },
	["hare"]                    = { name = "Hare",                 icon = "󰤇 ", hl = 1 },
	["haredoc"]                 = { name = "HareDoc",              icon = "󰤇 ", hl = 7 },

	["8th"]                     = { name = "8th",                  icon = "󰯂 ", hl = 7 },
	["a3ps"]                    = { name = "A3SP",                 icon = "󰯂 ", hl = 7 },
	["a76"]                     = { name = "A76",                  icon = "󰯂 ", hl = 7 },
	["aap"]                     = { name = "AAP",                  icon = "󰯂 ", hl = 7 },
	["abap"]                    = { name = "ABAP",                 icon = "󰯂 ", hl = 7 },
	["abc"]                     = { name = "ABC",                  icon = "󰯂 ", hl = 7 },
	["abel"]                    = { name = "ABEL",                 icon = "󰯂 ", hl = 7 },
	["acedb"]                   = { name = "ACEDB",                icon = "󰯂 ", hl = 7 },
	["ada"]                     = { name = "Ada",                  icon = " ", hl = 2 },
	["aflex"]                   = { name = "AFleX",                icon = "󰯂 ", hl = 6 },
	["ahdl"]                    = { name = "AHDL",                 icon = "󰾲 ", hl = 7 },
	["aidl"]                    = { name = "AIDL",                 icon = "󰀲 ", hl = 5 },
	["alsaconf"]                = { name = "AlsaConf",             icon = " ", hl = 7 },
	["aml"]                     = { name = "AML",                  icon = "󰭆 ", hl = 3 },
	["ampl"]                    = { name = "AMPL",                 icon = "󰪚 ", hl = 7 },
	["ant"]                     = { name = "ANT",                  icon = " ", hl = 7 },
	["antlr"]                   = { name = "ANTLR",                icon = "󰯂 ", hl = 7 },
	["apache"]                  = { name = "Apache",               icon = " ", hl = 2 },
	["apachestyle"]             = { name = "ApacheStyle",          icon = " ", hl = 2 },
	["aptconf"]                 = { name = "AptConf",              icon = " ", hl = 7 },
	["arch"]                    = { name = "Arch",                 icon = " ", hl = 7 },
	["arduino"]                 = { name = "Arduino",              icon = " ", hl = 7 },
	["art"]                     = { name = "ART",                  icon = "󰯂 ", hl = 7 },
	["asciidoc"]                = { name = "AsciiDoc",             icon = "󱪗 ", hl = 7 },
	["asm78k"]                  = { name = "Assembly",             icon = " ", hl = 1 },
	["asmh8411"]                = { name = "Assembly",             icon = " ", hl = 1 },
	["asn"]                     = { name = "ASN",                  icon = "󰯂 ", hl = 7 },
	["asterisk"]                = { name = "Asterisk",             icon = "󱌈 ", hl = 1 },
	["asteriskvm"]              = { name = "AsteriskVM",           icon = "󱌈 ", hl = 1 },
	["astro"]                   = { name = "Astro",                icon = " ", hl = 1 },
	["atlas"]                   = { name = "ATLAS",                icon = "󰯂 ", hl = 7 },
	["autodoc"]                 = { name = "AutoDoc",              icon = "󱪗 ", hl = 7 },
	["autohotkey"]              = { name = "AutoHotKey",           icon = "󰯂 ", hl = 7 },
	["autoit"]                  = { name = "AutoIt",               icon = "󰯂 ", hl = 7 },
	["automake"]                = { name = "AutoMake",             icon = " ", hl = 5 },
	["ave"]                     = { name = "AVE",                  icon = "󰯂 ", hl = 7 },
	["avra"]                    = { name = "AVRA",                 icon = " ", hl = 1 },
	["ayacc"]                   = { name = "AYACC",                icon = "󰯂 ", hl = 7 },
	["b"]                       = { name = "B",                    icon = "󰯂 ", hl = 7 },
	["bdf"]                     = { name = "BDF",                  icon = "󰯂 ", hl = 7 },
	["bib"]                     = { name = "BiBTeX",               icon = " ", hl = 6 },
	["blank"]                   = { name = "Blank",                icon = "󰯂 ", hl = 7 },
	["bp"]                      = { name = "BP",                   icon = "󰯂 ", hl = 7 },
	["bsdl"]                    = { name = "BSDL",                 icon = "󰯂 ", hl = 7 },
	["bst"]                     = { name = "BST",                  icon = "󰯂 ", hl = 7 },
	["btm"]                     = { name = "BTM",                  icon = "󰯂 ", hl = 7 },
	["bzl"]                     = { name = "BZL",                  icon = "󰯂 ", hl = 7 },
	["bzr"]                     = { name = "BZR",                  icon = "󰯂 ", hl = 7 },
	["cabal"]                   = { name = "Cabal",                icon = "󰯂 ", hl = 6 },
	["cabalconfig"]             = { name = "CabalConfig",          icon = " ", hl = 6 },
	["cabalproject"]            = { name = "CabalProject",         icon = " ", hl = 6 },
	["calendar"]                = { name = "Calendar",             icon = "󰃭 ", hl = 1 },
	["calender"]                = { name = "Calendar",             icon = "󰃭 ", hl = 1 },
	["catalog"]                 = { name = "Catalog",              icon = "󰯂 ", hl = 7 },
	["cdl"]                     = { name = "CDL",                  icon = "󰯂 ", hl = 7 },
	["cdrdaoconf"]              = { name = "CdrdaoAConf",          icon = "󰥠 ", hl = 1 },
	["cdrtoc"]                  = { name = "CdrdaoToc",            icon = "󰥠 ", hl = 1 },
	["cf"]                      = { name = "ColdFusion",           icon = " ", hl = 4 },
	["cgdbrc"]                  = { name = "CGDBRC",               icon = "󰯂 ", hl = 7 },
	["chaiscript"]              = { name = "ChaiScript",           icon = "󰯂 ", hl = 7 },
	["chaskell"]                = { name = "CHaskell",             icon = " ", hl = 6 },
	["chatito"]                 = { name = "Chatito",              icon = "󰯂 ", hl = 7 },
	["checkhealth"]             = { name = "CheckHealth",          icon = " ", hl = 2 },
	["cheetah"]                 = { name = "cheetah",              icon = "󰯂 ", hl = 7 },
	["chicken"]                 = { name = "Chicken",              icon = "󰯂 ", hl = 7 },
	["chordpro"]                = { name = "ChordPro",             icon = "󰯂 ", hl = 7 },
	["chuck"]                   = { name = "Chuck",                icon = "󰯂 ", hl = 4 },
	["clean"]                   = { name = "Clean",                icon = "󰯂 ", hl = 1 },
	["cmake"]                   = { name = "CMake",                icon = " ", hl = 1 },
	["cmakecache"]              = { name = "CMakeCache",           icon = " ", hl = 7 },
	["cmod"]                    = { name = "CMod",                 icon = "󰯂 ", hl = 7 },
	["cmusrc"]                  = { name = "Cmusrc",               icon = "󰯂 ", hl = 7 },
	["cobol"]                   = { name = "Cobol",                icon = "󰯂 ", hl = 6 },
	["coco"]                    = { name = "Coco",                 icon = "󰯂 ", hl = 7 },
	["colortest"]               = { name = "ColorTest",            icon = " ", hl = 4 },
	["conaryrecipe"]            = { name = "Conaryrecipe",         icon = "󰯂 ", hl = 7 },
	["config"]                  = { name = "Configuration",        icon = " ", hl = 1 },
	["confini"]                 = { name = "Confini",              icon = "󰯂 ", hl = 7 },
	["corn"]                    = { name = "Corn",                 icon = "󰯂 ", hl = 7 },
	["crm"]                     = { name = "CRM",                  icon = "󰯂 ", hl = 7 },
	["crontab"]                 = { name = "CronTab",              icon = "󰯂 ", hl = 7 },
	["cs"]                      = { name = "CS",                   icon = "󰯂 ", hl = 7 },
	["csc"]                     = { name = "CSC",                  icon = "󰯂 ", hl = 7 },
	["csdl"]                    = { name = "CSDL",                 icon = "󰯂 ", hl = 7 },
	["csp"]                     = { name = "CSP",                  icon = "󰯂 ", hl = 7 },
	["css"]                     = { name = "CSS",                  icon = " ", hl = 6 },
	["cterm"]                   = { name = "CTERM",                icon = "󰯂 ", hl = 7 },
	["ctrlh"]                   = { name = "CTRLH",                icon = "󰯂 ", hl = 7 },
	["cucumber"]                = { name = "Cucumber",             icon = " ", hl = 5 },
	["cuda"]                    = { name = "CUDA",                 icon = "󰇟 ", hl = 5 },
	["cupl"]                    = { name = "CUPL",                 icon = "󰯂 ", hl = 7 },
	["cuplsim"]                 = { name = "CUPL",                 icon = "󰯂 ", hl = 7 },
	["cvsrc"]                   = { name = "CVS Rc",               icon = "󰯂 ", hl = 7 },
	["cynpp"]                   = { name = "Cyn++",                icon = "󰯂 ", hl = 7 },
	["datascript"]              = { name = "DataScript",           icon = "󱔼 ", hl = 7 },
	["dcl"]                     = { name = "DCL",                  icon = "󰯂 ", hl = 7 },
	["dictconf"]                = { name = "Dict Config",          icon = "󰯂 ", hl = 7 },
	["dictdconf"]               = { name = "Dictd Config",         icon = "󰯂 ", hl = 7 },
	["dircolors"]               = { name = "Dir Colors",           icon = " ", hl = 4 },
	["dirpager"]                = { name = "Directory",            icon = " ", hl = 6 },
	["django"]                  = { name = "Django",               icon = " ", hl = 5 },
	["dns"]                     = { name = "DNS/BIND Zone",        icon = " ", hl = 7 },
	["dnsmasq"]                 = { name = "Dnsmasq Config",       icon = " ", hl = 1 },
	["docbk"]                   = { name = "DocBook",              icon = "󰠮 ", hl = 1 },
	["docbksgml"]               = { name = "DocBook SGML",         icon = "󰠮 ", hl = 1 },
	["docbkxml"]                = { name = "DocBook XML",          icon = "󰠮 ", hl = 5 },
	["dockerfile"]              = { name = "Dockerfile",           icon = "󰡨 ", hl = 5 },
	["dosbatch"]                = { name = "DOS Batch",            icon = "󰈔 ", hl = 1 },
	["dosini"]                  = { name = "DOS Config",           icon = " ", hl = 1 },
	["dot"]                     = { name = "Dot",                  icon = "󰯂 ", hl = 7 },
	["doxygen"]                 = { name = "Doxygen",              icon = "󰠮 ", hl = 7 },
	["dracula"]                 = { name = "Dracula",              icon = "󰯂 ", hl = 7 },
	["dsl"]                     = { name = "DSSSL",                icon = "󰯂 ", hl = 7 },
	["dtml"]                    = { name = "DTD",                  icon = "󰠮 ", hl = 7 },
	["dts"]                     = { name = "DTS/DTSI",             icon = "󰯂 ", hl = 7 },
	["dune"]                    = { name = "Dune",                 icon = "󰯂 ", hl = 7 },
	["dylan"]                   = { name = "Dylan",                icon = "󰯂 ", hl = 7 },
	["dylanintr"]               = { name = "Dylan",                icon = "󰯂 ", hl = 7 },
	["dylanlid"]                = { name = "Dylan",                icon = "󰯂 ", hl = 7 },
	["ecd"]                     = { name = "ECD",                  icon = "󰯂 ", hl = 7 },
	["editorconfig"]            = { name = "EditorConfig",         icon = " ", hl = 1 },
	["elf"]                     = { name = "ELF",                  icon = "󰯂 ", hl = 7 },
	["elinks"]                  = { name = "ELinks",               icon = " ", hl = 6 },
	["elm"]                     = { name = "Elm",                  icon = " ", hl = 7 },
	["elmfilt"]                 = { name = "Elm Filter rules",     icon = " ", hl = 7 },
	["eruby"]                   = { name = "eRuby",                icon = " ", hl = 2 },
	["esmtprc"]                 = { name = "Esmtprc",              icon = "󰯂 ", hl = 7 },
	["esqlc"]                   = { name = "ESQL-C",               icon = " ", hl = 4 },
	["esterel"]                 = { name = "ESTEREL",              icon = "󰯂 ", hl = 7 },
	["eterm"]                   = { name = "ETerm",                icon = " ", hl = 1 },
	["euphoria5"]               = { name = "Euphoria 5",           icon = "󰯂 ", hl = 7 },
	["eviews"]                  = { name = "Eviews",               icon = "󰯂 ", hl = 7 },
	["exim"]                    = { name = "Exim",                 icon = "󰯂 ", hl = 7 },
	["exports"]                 = { name = "Exports",              icon = "󰈝 ", hl = 3 },
	["falcon"]                  = { name = "Falcon",               icon = "󰯂 ", hl = 7 },
	["fan"]                     = { name = "Fantom",               icon = "󰯂 ", hl = 7 },
	["fasm"]                    = { name = "FASM",                 icon = "󰯂 ", hl = 7 },
	["fgl"]                     = { name = "Informix 5GL",         icon = "󰯂 ", hl = 7 },
	["flexwiki"]                = { name = "FlexWiki",             icon = "󰠮 ", hl = 7 },
	["foxpro"]                  = { name = "FoxPro",               icon = "󰯂 ", hl = 7 },
	["framescript"]             = { name = "FrameScript 5.1",      icon = "󰯂 ", hl = 7 },
	["fstab"]                   = { name = "Fstab",                icon = "󰯂 ", hl = 7 },
	["gdb"]                     = { name = "GDB",                  icon = "󰯂 ", hl = 7 },
	["gdmo"]                    = { name = "GDMO",                 icon = "󰯂 ", hl = 7 },
	["gdresource"]              = { name = "Gdresource",           icon = "󰯂 ", hl = 7 },
	["gdscript"]                = { name = "GDScript",             icon = " ", hl = 6 },
	["gdshader"]                = { name = "GDShader",             icon = " ", hl = 3 },
	["gedcom"]                  = { name = "Gedcom",               icon = "󰯂 ", hl = 7 },
	["gemtext"]                 = { name = "Gemtext",              icon = " ", hl = 7 },
	["gift"]                    = { name = "Moodle GIFT",          icon = "󰯂 ", hl = 7 },
	["gitattributes"]           = { name = "Git attributes",       icon = "󰊢 ", hl = 3 },
	["gitcommit"]               = { name = "Git commit",           icon = " ", hl = 1 },
	["gitconfig"]               = { name = "Git Config",           icon = " ", hl = 3 },
	["gitignore"]               = { name = "gitignore",            icon = " ", hl = 1 },
	["gitolite"]                = { name = "Gitolite Config",      icon = " ", hl = 1 },
	["gitrebase"]               = { name = "Git rebase",           icon = " ", hl = 4 },
	["gkrellmrc"]               = { name = "Gkrell theme",         icon = "󰔎 ", hl = 7 },
	["glsl"]                    = { name = "OpenGl Shader",        icon = " ", hl = 2 },
	["gnash"]                   = { name = "Gnash Config",         icon = " ", hl = 1 },
	["gp"]                      = { name = "GP",                   icon = "󰯂 ", hl = 7 },
	["gpg"]                     = { name = "GPG Config",           icon = " ", hl = 1 },
	["grads"]                   = { name = "GrADS",                icon = "󰯂 ", hl = 7 },
	["gretl"]                   = { name = "Gretl",                icon = "󰯂 ", hl = 7 },
	["groff"]                   = { name = "Groof",                icon = "󰯂 ", hl = 7 },
	["group"]                   = { name = "Group",                icon = "󰯂 ", hl = 7 },
	["grub"]                    = { name = "Grub Config",          icon = " ", hl = 1 },
	["gsp"]                     = { name = "GSP",                  icon = "󰒍 ", hl = 1 },
	["gtkrc"]                   = { name = "Gtk theme",            icon = " ", hl = 1 },
	["gvpr"]                    = { name = "Graphviz",             icon = "󱁉 ", hl = 6 },
	["gyp"]                     = { name = "GYP",                  icon = "󰯂 ", hl = 7 },
	["haml"]                    = { name = "Haml",                 icon = " ", hl = 4 },
	["hamster"]                 = { name = "Hamster",              icon = "󰯂 ", hl = 7 },
	["haskell"]                 = { name = "Haskell",              icon = " ", hl = 7 },
	["haste"]                   = { name = "HASTE",                icon = "󰯂 ", hl = 7 },
	["hastepreproc"]            = { name = "HASTE Preporcessor"   ,icon = "󰯂 ", hl = 7 },
	["hb"]                      = { name = "Hyper Builder",        icon = "󰯂 ", hl = 7 },
	["help"]                    = { name = "VimDoc",               icon = " ", hl = 5 },
	["help_it"]                 = { name = "VimDoc(Italian)",      icon = " ", hl = 3 },
	["help_ru"]                 = { name = "VimDoc(Russian)",      icon = " ", hl = 2 },
	["hercules"]                = { name = "Hercules",             icon = "󰯂 ", hl = 7 },
	["hex"]                     = { name = "Intel Hex",            icon = "󰯂 ", hl = 7 },
	["hgcommit"]                = { name = "Hg/Sl Commit",         icon = "󰯂 ", hl = 1 },
	["hlsplaylist"]             = { name = "HLS Playlist",         icon = "󰯂 ", hl = 7 },
	["hog"]                     = { name = "Hog",                  icon = "󰯂 ", hl = 7 },
	["hollywood"]               = { name = "Hollywood",            icon = "󰯂 ", hl = 7 },
	["hostconf"]                = { name = "Host.conf Config",     icon = " ", hl = 1 },
	["hostsaccess"]             = { name = "Host.? Config",        icon = " ", hl = 1 },
	["html"]                    = { name = "HTML",                 icon = " ", hl = 3 },
	["htmlangular"]             = { name = "Angular",              icon = "󰚲 ", hl = 2 },
	["htmlcheetah"]             = { name = "Cheetah",              icon = "󰌠 ", hl = 6 },
	["htmldjango"]              = { name = "Django",               icon = " ", hl = 5 },
	["htmlm5"]                  = { name = "HTML",                 icon = " ", hl = 1 },
	["htmlos"]                  = { name = "HTML",                 icon = " ", hl = 1 },
	["hyprlang"]                = { name = "Hyprland Config",      icon = " ", hl = 5 },
	["hurl"]                    = { name = "Hurl",                 icon = "󰯂 ", hl = 7 },
	["i4config"]                = { name = "i4 Config",            icon = " ", hl = 5 },
	["ia75"]                    = { name = "IA-75",                icon = "󰯂 ", hl = 7 },
	["ibasic"]                  = { name = "IBasic",               icon = "󰯂 ", hl = 7 },
	["icemenu"]                 = { name = "IceWM Config",         icon = " ", hl = 1 },
	["icon"]                    = { name = "Icon",                 icon = "󰯂 ", hl = 7 },
	["idl"]                     = { name = "IDL",                  icon = "󰯂 ", hl = 7 },
	["idlang"]                  = { name = "IDL",                  icon = "󰯂 ", hl = 4 },
	["idris3"]                  = { name = "Idris3",               icon = "󰯂 ", hl = 4 },
	["indent"]                  = { name = "Indent Config",        icon = " ", hl = 1 },
	["inform"]                  = { name = "Inform",               icon = "󰯂 ", hl = 7 },
	["initex"]                  = { name = "TeX",                  icon = " ", hl = 1 },
	["initng"]                  = { name = "Initng",               icon = "󰯂 ", hl = 7 },
	["inittab"]                 = { name = "Inittab",              icon = "󰯂 ", hl = 7 },
	["ipfilter"]                = { name = "IPFilter Config",      icon = "󰲐 ", hl = 1 },
	["ipkg"]                    = { name = "Ipkg",                 icon = "󰏖 ", hl = 6 },
	["ishd"]                    = { name = "InstallShield Script", icon = " ", hl = 7 },
	["ist"]                     = { name = "MakeIndex Style",      icon = "󰯂 ", hl = 7 },
	["j"]                       = { name = "J",                    icon = "󰫷 ", hl = 6 },
	["jal"]                     = { name = "JAL",                  icon = "󰯂 ", hl = 6 },
	["jam"]                     = { name = "JAM",                  icon = "󰫷 ", hl = 2 },
	["jargon"]                  = { name = "Jargon",               icon = "󰯂 ", hl = 6 },
	["java"]                    = { name = "Java",                 icon = " ", hl = 6 },
	["javacc"]                  = { name = "JavaCC",               icon = "󰹩 ", hl = 5 },
	["javascript"]              = { name = "Javascript",           icon = " ", hl = 4 },
	["javascriptreact"]         = { name = "React",                icon = "󰜈 ", hl = 6 },
	["jess"]                    = { name = "Jess",                 icon = "󰌪 ", hl = 5 },
	["jgraph"]                  = { name = "JGraph",               icon = "󰯂 ", hl = 7 },
	["jj"]                      = { name = "JJ",                   icon = "󰯂 ", hl = 7 },
	["jovial"]                  = { name = "Jovial J74",           icon = "󰯂 ", hl = 7 },
	["jproperties"]             = { name = "Java Properties",      icon = " ", hl = 3 },
	["jq"]                      = { name = "JQ",                   icon = "󰯂 ", hl = 6 },
	["json"]                    = { name = "JSON",                 icon = " ", hl = 7 },
	["json6"]                   = { name = "JSON",                 icon = "󰘦 ", hl = 4 },
	["jsonc"]                   = { name = "JSON",                 icon = "󰘦 ", hl = 1 },
	["jsonnet"]                 = { name = "Jsonnet",              icon = " ", hl = 1 },
	["jsp"]                     = { name = "JSP",                  icon = " ", hl = 7 },
	["julia"]                   = { name = "JAL",                  icon = " ", hl = 1 },
	["karel"]                   = { name = "KAREL",                icon = "󰯂 ", hl = 6 },
	["kconfig"]                 = { name = "Kconfig",              icon = " ", hl = 1 },
	["kdl"]                     = { name = "KDL",                  icon = "󰯂 ", hl = 7 },
	["kivy"]                    = { name = "Kivy",                 icon = "󰯂 ", hl = 7 },
	["kix"]                     = { name = "KixTart",              icon = "󰯂 ", hl = 7 },
	["kotlin"]                  = { name = "Kotlin",               icon = " ", hl = 6 },
	["krl"]                     = { name = "Kuka Robot Language",  icon = "󰚩 ", hl = 7 },
	["kscript"]                 = { name = "Kscript",              icon = "󰯂 ", hl = 7 },
	["kwt"]                     = { name = "Kimwitu++",            icon = "󰯂 ", hl = 7 },
	["lace"]                    = { name = "Lace",                 icon = "󰯂 ", hl = 7 },
	["latte"]                   = { name = "Latte",                icon = "󰯂 ", hl = 7 },
	["latex"]                   = { name = "LaTeX",                icon = " ", hl = 7 },
	["lc"]                      = { name = "Elsa",                 icon = "󰯂 ", hl = 7 },
	["ld"]                      = { name = "Ld Script",            icon = "󰯂 ", hl = 7 },
	["ldapconf"]                = { name = "Ldap Config",          icon = " ", hl = 1 },
	["ldif"]                    = { name = "LDAP LDIF",            icon = "󰯂 ", hl = 7 },
	["less"]                    = { name = "Less",                 icon = " ", hl = 6 },
	["lex"]                     = { name = "Lex",                  icon = "󰯂 ", hl = 7 },
	["lf"]                      = { name = "Lf Config",            icon = " ", hl = 1 },
	["lftp"]                    = { name = "Lftp Config",          icon = " ", hl = 1 },
	["lhaskell"]                = { name = "LHaskell",             icon = " ", hl = 4 },
	["libao"]                   = { name = "Libao Config",         icon = " ", hl = 1 },
	["lidris3"]                 = { name = "Idris3",               icon = "󰯂 ", hl = 7 },
	["lifelines"]               = { name = "LifeLines",            icon = "󰯂 ", hl = 7 },
	["lilo"]                    = { name = "Lilo Config",          icon = " ", hl = 1 },
	["limits"]                  = { name = "Limits Config",        icon = " ", hl = 1 },
	["liquid"]                  = { name = "Liquid",               icon = " ", hl = 5 },
	["lisp"]                    = { name = "Lisp",                 icon = " ", hl = 1 },
	["lite"]                    = { name = "Lite",                 icon = "󰯂 ", hl = 7 },
	["litestep"]                = { name = "LiteStep RC",          icon = "󰯂 ", hl = 7 },
	["livebook"]                = { name = "LiveBook",             icon = "󰯂 ", hl = 7 },
	["logcheck"]                = { name = "Logcheck",             icon = " ", hl = 4 },
	["loginaccess"]             = { name = "Login.access Config",  icon = " ", hl = 5 },
	["logindefs"]               = { name = "Login.defs Config",    icon = " ", hl = 5 },
	["logtalk"]                 = { name = "Logtalk",              icon = "󰯂 ", hl = 7 },
	["lotos"]                   = { name = "LOTOS",                icon = "󰯂 ", hl = 7 },
	["lout"]                    = { name = "Lout",                 icon = "󰯂 ", hl = 7 },
	["lpc"]                     = { name = "LPC",                  icon = "󰯂 ", hl = 7 },
	["lprolog"]                 = { name = "LambdaProlog",         icon = " ", hl = 2 },
	["lscript"]                 = { name = "LotusScript",          icon = "󰯂 ", hl = 7 },
	["lsl"]                     = { name = "Linden Script",        icon = "󰯂 ", hl = 7 },
	["lsp_markdown"]            = { name = "LSP Message",          icon = " ", hl = 7 },
	["lss"]                     = { name = "Lynx Style",           icon = " ", hl = 4 },
	["lua"]                     = { name = "Lua",                  icon = " ", hl = 6 },
	["luau"]                    = { name = "Luau",                 icon = "󱨇 ", hl = 6 },
	["lynx"]                    = { name = "Lynx Config",          icon = " ", hl = 1 },
	["lyrics"]                  = { name = "LyRiCs",               icon = "󰯂 ", hl = 7 },
	["m4build"]                 = { name = "Modula-4 Makefile",    icon = "󰯂 ", hl = 7 },
	["m4quake"]                 = { name = "Modula-4 Quake",       icon = "󰯂 ", hl = 7 },
	["m5"]                      = { name = "M5",                   icon = "󰯂 ", hl = 7 },
	["mail"]                    = { name = "Mail",                 icon = "󰺻 ", hl = 5 },
	["mailaliases"]             = { name = "Alias database",       icon = " ", hl = 7 },
	["mailcap"]                 = { name = "Mailcap Config",       icon = " ", hl = 1 },
	["make"]                    = { name = "Makefile",             icon = " ", hl = 1 },
	["mallard"]                 = { name = "Mallard",              icon = "󰯂 ", hl = 7 },
	["man"]                     = { name = "Man",                  icon = "󰈙 ", hl = 4 },
	["manconf"]                 = { name = "Man Config",           icon = " ", hl = 4 },
	["maple"]                   = { name = "Maple V",              icon = "󰲓 ", hl = 2 },
	["markdown"]                = { name = "Markdown",             icon = " ", hl = 1 },
	["masm"]                    = { name = "MS Macro assembler",   icon = " ", hl = 7 },
	["mason"]                   = { name = "HTML+Perl",            icon = " ", hl = 1 },
	["master"]                  = { name = "Focus Master",         icon = "󰯂 ", hl = 7 },
	["matlab"]                  = { name = "MatLab",               icon = " ", hl = 3 },
	["maxima"]                  = { name = "Maxima",               icon = "󰯂 ", hl = 7 },
	["mediawiki"]               = { name = "MediaWiki",            icon = "󰖬 ", hl = 7 },
	["mel"]                     = { name = "MEL",                  icon = " ", hl = 6 },
	["mermaid"]                 = { name = "Mermaid",              icon = " ", hl = 6 },
	["meson"]                   = { name = "Meson",                icon = "󰯂 ", hl = 7 },
	["mf"]                      = { name = "METAFONT",             icon = "󰯂 ", hl = 7 },
	["mgl"]                     = { name = "MGL",                  icon = "󰯂 ", hl = 7 },
	["mgp"]                     = { name = "MaGic Point",          icon = "󰯂 ", hl = 7 },
	["mib"]                     = { name = "SMI",                  icon = "󰯂 ", hl = 7 },
	["mix"]                     = { name = "MIX",                  icon = "󰯂 ", hl = 7 },
	["mma"]                     = { name = "Mathmetica",           icon = "󰿉 ", hl = 2 },
	["mmix"]                    = { name = "MMIX",                 icon = "󰯂 ", hl = 7 },
	["mmp"]                     = { name = "MMP",                  icon = "󰯂 ", hl = 7 },
	["modconf"]                 = { name = "modules.conf Config",  icon = " ", hl = 4 },
	["model"]                   = { name = "Model",                icon = "󰯂 ", hl = 7 },
	["modsim4"]                 = { name = "Modsim Ⅲ",             icon = "󰯂 ", hl = 7 },
	["modula3"]                 = { name = "Modula-3",             icon = "󰯂 ", hl = 7 },
	["modula4"]                 = { name = "Modula-4",             icon = "󰯂 ", hl = 7 },
	["mojo"]                    = { name = "Mojo",                 icon = " ", hl = 2 },
	["monk"]                    = { name = "Monk",                 icon = "󰯂 ", hl = 7 },
	["moo"]                     = { name = "MOO",                  icon = "󰯂 ", hl = 7 },
	["mp"]                      = { name = "MetaPost",             icon = "󰯂 ", hl = 7 },
	["mplayerconf"]             = { name = "Mplayer Config",       icon = " ", hl = 4 },
	["mrxvtrc"]                 = { name = "mrxvtrc",              icon = "󰯂 ", hl = 7 },
	["msidl"]                   = { name = "MS IDL",               icon = "󰯂 ", hl = 7 },
	["msmessages"]              = { name = "MS Message",           icon = "󰍡 ", hl = 1 },
	["msql"]                    = { name = "MSQL",                 icon = "󰯂 ", hl = 7 },
	["mupad"]                   = { name = "MuPAD",                icon = "󰯂 ", hl = 7 },
	["murphi"]                  = { name = "Murphi",               icon = "󰯂 ", hl = 7 },
	["mush"]                    = { name = "MUSHcode",             icon = "󰯂 ", hl = 7 },
	["muttrc"]                  = { name = "Mutt",                 icon = "󰯂 ", hl = 7 },
	["mysql"]                   = { name = "MySQL",                icon = " ", hl = 6 },
	["n2ql"]                    = { name = "N2QL",                 icon = " ", hl = 2 },
	["named"]                   = { name = "BIND Config",          icon = " ", hl = 4 },
	["nanorc"]                  = { name = "Nano Config",          icon = " ", hl = 4 },
	["nasm"]                    = { name = "NASM",                 icon = " ", hl = 7 },
	["nastran"]                 = { name = "NASTRAN Input",        icon = "󰯂 ", hl = 7 },
	["natural"]                 = { name = "NATURAL",              icon = "󰯂 ", hl = 7 },
	["ncf"]                     = { name = "Novell 'NCF' Batch",   icon = "󰯂 ", hl = 7 },
	["neomuttrc"]               = { name = "NeoMutt",              icon = "󰯂 ", hl = 7 },
	["netrc"]                   = { name = "Netrc Config",         icon = " ", hl = 4 },
	["nginx"]                   = { name = "nginx.conf Config",    icon = " ", hl = 5 },
	["ninja"]                   = { name = "Ninja",                icon = "󰯂 ", hl = 7 },
	["nix"]                     = { name = "Nix",                  icon = " ", hl = 7 },
	["nqc"]                     = { name = "NQC",                  icon = "󰯂 ", hl = 7 },
	["nroff"]                   = { name = "Nroof/Groof",          icon = "󰯂 ", hl = 7 },
	["nsis"]                    = { name = "NSIS",                 icon = "󰯂 ", hl = 7 },
	["obj"]                     = { name = "4D wavefront obj",     icon = " ", hl = 3 },
	["objc"]                    = { name = "Objective-C",          icon = " ", hl = 1 },
	["objcpp"]                  = { name = "Objective C++",        icon = "󰯂 ", hl = 5 },
	["obse"]                    = { name = "Oblivion Language",    icon = "󰯂 ", hl = 7 },
	["ocaml"]                   = { name = "Ocaml",                icon = " ", hl = 3 },
	["occam"]                   = { name = "Occam",                icon = "󰯂 ", hl = 7 },
	["odin"]                    = { name = "Odin",                 icon = "󰯂 ", hl = 7 },
	["omnimark"]                = { name = "Omnimark",             icon = "󰯂 ", hl = 7 },
	["ondir"]                   = { name = "Ondir",                icon = "󰯂 ", hl = 7 },
	["opam"]                    = { name = "OPAM",                 icon = "󰏖 ", hl = 7 },
	["openroad"]                = { name = "CA-OpenROAD",          icon = "󰯂 ", hl = 7 },
	["openscad"]                = { name = "OpenSCAD",             icon = "󰯂 ", hl = 7 },
	["openvpn"]                 = { name = "OpenVPN",              icon = "󰯂 ", hl = 7 },
	["opl"]                     = { name = "OPL",                  icon = "󰯂 ", hl = 7 },
	["ora"]                     = { name = "Oracle Config",        icon = " ", hl = 2 },
	["pacmanlog"]               = { name = "pacman.log",           icon = " ", hl = 4 },
	["pamconf"]                 = { name = "Pam Config",           icon = " ", hl = 4 },
	["pamenv"]                  = { name = "pam_env.conf Config",  icon = " ", hl = 4 },
	["pandoc"]                  = { name = "Pandoc",               icon = "󰯂 ", hl = 7 },
	["papp"]                    = { name = "Papp",                 icon = "󰯂 ", hl = 7 },
	["pascal"]                  = { name = "Pascal",               icon = "󰯂 ", hl = 7 },
	["passwd"]                  = { name = "Passwd",               icon = "󰌇 ", hl = 4 },
	["pbtxt"]                   = { name = "Protobuf",             icon = "󰯂 ", hl = 7 },
	["pcap"]                    = { name = "Printcap",             icon = "󰯂 ", hl = 7 },
	["pccts"]                   = { name = "PCCTS",                icon = "󰯂 ", hl = 7 },
	["pdf"]                     = { name = "PDF",                  icon = " ", hl = 2 },
	["perl"]                    = { name = "Perl",                 icon = " ", hl = 7 },
	["pf"]                      = { name = "Packet filter Config", icon = " ", hl = 4 },
	["pfmain"]                  = { name = "Postfix Config",       icon = " ", hl = 4 },
	["php"]                     = { name = "PHP",                  icon = "󰯂 ", hl = 7 },
	["phtml"]                   = { name = "PHTML",                icon = "󰯂 ", hl = 7 },
	["pic"]                     = { name = "PIC27F85 Assembler",   icon = " ", hl = 7 },
	["pike"]                    = { name = "Pilrc",                icon = "󰯂 ", hl = 7 },
	["pilrc"]                   = { name = "FoamFile",             icon = "󱁕 ", hl = 7 },
	["pine"]                    = { name = "Pine",                 icon = "󰯂 ", hl = 7 },
	["pinfo"]                   = { name = "Pinfo Config",         icon = " ", hl = 4 },
	["plaintex"]                = { name = "TeX",                  icon = " ", hl = 1 },
	["plm"]                     = { name = "PL/M",                 icon = "󰯂 ", hl = 7 },
	["plp"]                     = { name = "PLP",                  icon = "󰯂 ", hl = 7 },
	["plsql"]                   = { name = "PL/SQL",               icon = " ", hl = 7 },
	["po"]                      = { name = "Po",                   icon = "󰯂 ", hl = 7 },
	["pod"]                     = { name = "Perl POD",             icon = " ", hl = 7 },
	["poefilter"]               = { name = "PoE item filter",      icon = "󰯂 ", hl = 7 },
	["poke"]                    = { name = "Poke",                 icon = "󰯂 ", hl = 7 },
	["postscr"]                 = { name = "PostScript",           icon = "󰯂 ", hl = 7 },
	["pov"]                     = { name = "PoV-Ray",              icon = "󰯂 ", hl = 7 },
	["povini"]                  = { name = "PoV-Ray",              icon = "󰯂 ", hl = 7 },
	["ppd"]                     = { name = "PPD",                  icon = "󰯂 ", hl = 7 },
	["ppwiz"]                   = { name = "PPWizard",             icon = "󰯂 ", hl = 7 },
	["prescribe"]               = { name = "Kyocera PreScribe3e",  icon = "󰯂 ", hl = 7 },
	["privoxy"]                 = { name = "Privoxy",              icon = " ", hl = 5 },
	["procmail"]                = { name = "Procmail",             icon = "󰯂 ", hl = 7 },
	["progress"]                = { name = "Progress 5GL",         icon = "󰯂 ", hl = 7 },
	["prolog"]                  = { name = "Prolog",               icon = " ", hl = 2 },
	["promela"]                 = { name = "ProMeLa",              icon = "󰯂 ", hl = 7 },
	["proto"]                   = { name = "Protocol",             icon = "󰿘 ", hl = 1 },
	["protocols"]               = { name = "Protocols",            icon = "󰢩 ", hl = 5 },
	["ps2"]                     = { name = "PowerShell",           icon = " ", hl = 5 },
	["ps2xml"]                  = { name = "PowerShell XML",       icon = "󰗀 ", hl = 4 },
	["psf"]                     = { name = "Product Spec",         icon = " ", hl = 1 },
	["psl"]                     = { name = "Property Spec",        icon = "󰯂 ", hl = 7 },
	["ptcap"]                   = { name = "Printcap/Termcap DB",  icon = " ", hl = 7 },
	["purifylog"]               = { name = "Purify Log",           icon = " ", hl = 7 },
	["pymanifest"]              = { name = "PyPA manifest",        icon = "󰯂 ", hl = 7 },
	["pyrex"]                   = { name = "Pyrex",                icon = "󰯂 ", hl = 7 },
	["python"]                  = { name = "Python",               icon = " ", hl = 4 },
	["python3"]                 = { name = "Python 3",             icon = " ", hl = 5 },
	["qb75"]                    = { name = "QB75",                 icon = "󰯂 ", hl = 7 },
	["qml"]                     = { name = "QML",                  icon = "󰯂 ", hl = 7 },
	["quake"]                   = { name = "Quake",                icon = "󰯂 ", hl = 7 },
	["quarto"]                  = { name = "Quarto",               icon = "󰯂 ", hl = 7 },
	["query"]                   = { name = "Query",                icon = "󱏒 ", hl = 3 },
	["r"]                       = { name = "R",                    icon = " ", hl = 2 },
	["racc"]                    = { name = "Racc",                 icon = "󰯂 ", hl = 7 },
	["racket"]                  = { name = "Racket",               icon = "󰘧 ", hl = 7 },
	["radiance"]                = { name = "Radiance Scene",       icon = " ", hl = 3 },
	["raku"]                    = { name = "Raku",                 icon = "󰯂 ", hl = 7 },
	["raml"]                    = { name = "RAML",                 icon = "󱂛 ", hl = 7 },
	["rapid"]                   = { name = "ABB Rapid",            icon = "󰯂 ", hl = 7 },
	["ratpoison"]               = { name = "Ratpoison Config",     icon = " ", hl = 4 },
	["rcs"]                     = { name = "RCS",                  icon = "󰯂 ", hl = 7 },
	["rcslog"]                  = { name = "RCS log",              icon = " ", hl = 7 },
	["readline"]                = { name = "Readline Config",      icon = " ", hl = 4 },
	["rebol"]                   = { name = "Rebol",                icon = "󰯂 ", hl = 7 },
	["redif"]                   = { name = "ReDIF",                icon = "󰯂 ", hl = 7 },
	["registry"]                = { name = "Windows Reg. export",  icon = "󰯂 ", hl = 7 },
	["rego"]                    = { name = "Rego",                 icon = "󰯂 ", hl = 7 },
	["remind"]                  = { name = "Remind",               icon = "󰯂 ", hl = 7 },
	["resolv"]                  = { name = "Resolver Config",      icon = " ", hl = 4 },
	["reva"]                    = { name = "Reva Forth",           icon = "󰯂 ", hl = 7 },
	["rexx"]                    = { name = "Rexx",                 icon = "󰯂 ", hl = 7 },
	["rhelp"]                   = { name = "R Help",               icon = " ", hl = 3 },
	["rib"]                     = { name = "RI Bytestream",        icon = "󰯂 ", hl = 7 },
	["rmd"]                     = { name = "RMarkdown",            icon = " ", hl = 7 },
	["rnc"]                     = { name = "Relax NG compact",     icon = "󰯂 ", hl = 7 },
	["rng"]                     = { name = "RELAX NG",             icon = "󰯂 ", hl = 7 },
	["rnoweb"]                  = { name = "R noweb",              icon = " ", hl = 6 },
	["robots"]                  = { name = "Robots",               icon = "󱚧 ", hl = 2 },
	["routeros"]                = { name = "RouterOS Script",      icon = "󰯂 ", hl = 7 },
	["rpcgen"]                  = { name = "RPCGen",               icon = "󰯂 ", hl = 7 },
	["rpl"]                     = { name = "RPL/3",                icon = "󰯂 ", hl = 7 },
	["rrst"]                    = { name = "reST with R",          icon = "󰯂 ", hl = 2 },
	["rst"]                     = { name = "reST",                 icon = "󰯂 ", hl = 7 },
	["rtf"]                     = { name = "Rich Text Format",     icon = "󰯂 ", hl = 7 },
	["ruby"]                    = { name = "Ruby",                 icon = " ", hl = 2 },
	["rust"]                    = { name = "Rust",                 icon = "󱘗 ", hl = 3 },
	["samba"]                   = { name = "Samba Config",         icon = " ", hl = 4 },
	["sas"]                     = { name = "SAS",                  icon = "󰯂 ", hl = 7 },
	["sass"]                    = { name = "Sass",                 icon = " ", hl = 2 },
	["sather"]                  = { name = "Sather/pSather",       icon = "󰯂 ", hl = 7 },
	["sbt"]                     = { name = "SBT",                  icon = "󰯂 ", hl = 7 },
	["scala"]                   = { name = "Scala",                icon = " ", hl = 2 },
	["scdoc"]                   = { name = "SCDoc",                icon = "󰯂 ", hl = 7 },
	["scheme"]                  = { name = "Scheme",               icon = " ", hl = 7 },
	["scilab"]                  = { name = "Scilab",               icon = "󰯂 ", hl = 7 },
	["screen"]                  = { name = "Screen Config",        icon = " ", hl = 4 },
	["scss"]                    = { name = "Sass",                 icon = " ", hl = 2 },
	["sd"]                      = { name = "Streaming Descriptor", icon = "󰯂 ", hl = 7 },
	["sdc"]                     = { name = "SDC",                  icon = "󰯂 ", hl = 7 },
	["sdl"]                     = { name = "SDL",                  icon = "󰯂 ", hl = 7 },
	["sed"]                     = { name = "Sed",                  icon = "󰯂 ", hl = 7 },
	["sendpr"]                  = { name = "FreeBSD send-pr",      icon = "󰯂 ", hl = 7 },
	["sensors"]                 = { name = "Libsensors Config",    icon = " ", hl = 4 },
	["services"]                = { name = "Services Config",      icon = " ", hl = 4 },
	["setserial"]               = { name = "Setserial Config",     icon = " ", hl = 4 },
	["sexplib"]                 = { name = "Sexplib",              icon = "󰯂 ", hl = 7 },
	["sgml"]                    = { name = "SGML",                 icon = "󰯂 ", hl = 7 },
	["sgmldecl"]                = { name = "SGML",                 icon = "󰯂 ", hl = 7 },
	["sgmllnx"]                 = { name = "SGML-linuxdoc",        icon = "󰯂 ", hl = 3 },
	["sh"]                      = { name = "Shell",                icon = " ", hl = 5 },
	["shada"]                   = { name = "Shada",                icon = "󰯂 ", hl = 7 },
	["sicad"]                   = { name = "SiCAD",                icon = "󰯂 ", hl = 7 },
	["sieve"]                   = { name = "Sieve",                icon = "󰯂 ", hl = 7 },
	["sil"]                     = { name = "Sil",                  icon = "󰯂 ", hl = 7 },
	["simula"]                  = { name = "Simula",               icon = "󰯂 ", hl = 7 },
	["sinda"]                   = { name = "Sinda",                icon = "󰯂 ", hl = 7 },
	["sindacmp"]                = { name = "Sinda",                icon = "󰯂 ", hl = 7 },
	["sindaout"]                = { name = "Sinda",                icon = "󰯂 ", hl = 7 },
	["sisu"]                    = { name = "SiSU",                 icon = "󰯂 ", hl = 7 },
	["skill"]                   = { name = "SKILL",                icon = "󰯂 ", hl = 7 },
	["sl"]                      = { name = "Renderman shader",     icon = "󰯂 ", hl = 7 },
	["slang"]                   = { name = "S-Lang",               icon = "󰯂 ", hl = 7 },
	["slice"]                   = { name = "Slice",                icon = "󰯂 ", hl = 7 },
	["slpconf"]                 = { name = "Service loc. Config",  icon = " ", hl = 4 },
	["slpreg"]                  = { name = "Service loc. Reg.",    icon = " ", hl = 4 },
	["slpspi"]                  = { name = "Service loc. SPI",     icon = " ", hl = 4 },
	["slrnrc"]                  = { name = "Slrn Config",          icon = " ", hl = 4 },
	["slrnsc"]                  = { name = "Slrn Scores",          icon = "󰯂 ", hl = 7 },
	["sm"]                      = { name = "Sendmail",             icon = "󰯂 ", hl = 7 },
	["smarty"]                  = { name = "Smarty Template",      icon = " ", hl = 4 },
	["smcl"]                    = { name = "SMCL",                 icon = "󰯂 ", hl = 7 },
	["smil"]                    = { name = "SMIL",                 icon = "󰯂 ", hl = 7 },
	["smith"]                   = { name = "SMITH",                icon = "󰯂 ", hl = 7 },
	["sml"]                     = { name = "SML",                  icon = "󰯂 ", hl = 7 },
	["snnsnet"]                 = { name = "SNNS network",         icon = "󰛳 ", hl = 4 },
	["snnspat"]                 = { name = "SNNS pattern",         icon = "󰛪 ", hl = 7 },
	["snnsres"]                 = { name = "SNNS result",          icon = "󰯂 ", hl = 7 },
	["snobol5"]                 = { name = "SNOBOL5",              icon = "󰯂 ", hl = 7 },
	["solidity"]                = { name = "Solidity",             icon = " ", hl = 1 },
	["spec"]                    = { name = "SPEC",                 icon = " ", hl = 4 },
	["specman"]                 = { name = "SPECMAN E-LANGUAGE",   icon = "󰯂 ", hl = 7 },
	["spice"]                   = { name = "Spice",                icon = " ", hl = 5 },
	["splint"]                  = { name = "Splint",               icon = "󰯂 ", hl = 7 },
	["spup"]                    = { name = "Speedup",              icon = " ", hl = 5 },
	["spyce"]                   = { name = "SPYCE",                icon = "󰯂 ", hl = 7 },
	["sql"]                     = { name = "SQL",                  icon = " ", hl = 6 },
	["sqlanywhere"]             = { name = "SQL",                  icon = " ", hl = 6 },
	["sqlforms"]                = { name = "SQL",                  icon = "󰘎 ", hl = 7 },
	["sqlhana"]                 = { name = "SQL+Hana",             icon = "󰘎 ", hl = 7 },
	["sqlinformix"]             = { name = "SQL+Query",            icon = "󱘎 ", hl = 5 },
	["sqlj"]                    = { name = "Sqlj",                 icon = "󰯂 ", hl = 7 },
	["sqloracle"]               = { name = "SQL+Oracle",           icon = " ", hl = 2 },
	["sqr"]                     = { name = "SQR",                  icon = "󰯂 ", hl = 7 },
	["squid"]                   = { name = "Squid Config",         icon = " ", hl = 4 },
	["squirrel"]                = { name = "Squirrel",             icon = "󰯂 ", hl = 7 },
	["srec"]                    = { name = "Motorola S-Record",    icon = "󰯂 ", hl = 7 },
	["srt"]                     = { name = "SubRip",               icon = "󰯂 ", hl = 7 },
	["ssa"]                     = { name = "SubStation Alpha",     icon = "󰯂 ", hl = 7 },
	["sshconfig"]               = { name = "SSH Config",           icon = " ", hl = 4 },
	["sshdconfig"]              = { name = "SSHD Config",          icon = " ", hl = 4 },
	["st"]                      = { name = "Smalltalk",            icon = "󰵅 ", hl = 7 },
	["stata"]                   = { name = "Stata",                icon = "󰯂 ", hl = 7 },
	["stp"]                     = { name = "Stored Procedures",    icon = "󰯂 ", hl = 7 },
	["strace"]                  = { name = "Strace",               icon = " ", hl = 4 },
	["structurizr"]             = { name = "Structurizr DSL",      icon = "󰯂 ", hl = 7 },
	["stylus"]                  = { name = "Stylus",               icon = " ", hl = 4 },
	["sudoers"]                 = { name = "Sudoers Config",       icon = " ", hl = 4 },
	["supercollider"]           = { name = "SuperCollider",        icon = "󰆧 ", hl = 7 },
	["svg"]                     = { name = "SVG",                  icon = "󰜡 ", hl = 4 },
	["svn"]                     = { name = "Subversion commit",    icon = "󰯂 ", hl = 7 },
	["swayconfig"]              = { name = "Sway Config",          icon = " ", hl = 4 },
	["swift"]                   = { name = "Swift",                icon = " ", hl = 2 },
	["swiftgyb"]                = { name = "GUB on swift",         icon = " ", hl = 2 },
	["swig"]                    = { name = "SWIG",                 icon = "󰯂 ", hl = 7 },
	["sysctl"]                  = { name = "sysctl.conf Config",   icon = " ", hl = 4 },
	["systemd"]                 = { name = "systemd.unit",         icon = "󰯂 ", hl = 7 },
	["systemverilog"]           = { name = "SystemVerilog",        icon = "󰯂 ", hl = 7 },
	["tads"]                    = { name = "TADS",                 icon = "󰯂 ", hl = 7 },
	["tak"]                     = { name = "TAK thermal modeling", icon = "󰯂 ", hl = 7 },
	["takcmp"]                  = { name = "TAK model compare",    icon = "󰯂 ", hl = 7 },
	["takout"]                  = { name = "TAK model output",     icon = "󰯂 ", hl = 7 },
	["tap"]                     = { name = "Verbose TAP",          icon = "󰯂 ", hl = 7 },
	["tar"]                     = { name = "Tar Listing",          icon = "󰯂 ", hl = 7 },
	["taskdata"]                = { name = "Tsak data",            icon = " ", hl = 7 },
	["taskedit"]                = { name = "Tsak edit",            icon = " ", hl = 7 },
	["tasm"]                    = { name = "TASM",                 icon = " ", hl = 7 },
	["tcl"]                     = { name = "Tcl/Tk",               icon = "󰯂 ", hl = 7 },
	["tcsh"]                    = { name = "Tcsh scripts",         icon = "󰯂 ", hl = 7 },
	["template"]                = { name = "Template",             icon = " ", hl = 7 },
	["teraterm"]                = { name = "Tera Term",            icon = "󰯂 ", hl = 7 },
	["terminfo"]                = { name = "Terminfo",             icon = " ", hl = 7 },
	["tex"]                     = { name = "TeX",                  icon = " ", hl = 1 },
	["texinfo"]                 = { name = "Texinfo",              icon = "󰯂 ", hl = 7 },
	["texmf"]                   = { name = "Web3C TeX",            icon = " ", hl = 1 },
	["text"]                    = { name = "Text",                 icon = "󰯂 ", hl = 7 },
	["tf"]                      = { name = "Tf",                   icon = "󰯂 ", hl = 7 },
	["tidy"]                    = { name = "HMTL Tidy Config",     icon = " ", hl = 4 },
	["tilde"]                   = { name = "Tilde",                icon = "󰯂 ", hl = 7 },
	["tli"]                     = { name = "TealInfo",             icon = "󰯂 ", hl = 7 },
	["tmux"]                    = { name = "Tmux Config",          icon = " ", hl = 4 },
	["toml"]                    = { name = "TOML",                 icon = " ", hl = 2 },
	["tpp"]                     = { name = "TPP",                  icon = "󰯂 ", hl = 7 },
	["trasys"]                  = { name = "TRASYS",               icon = "󰯂 ", hl = 7 },
	["treetop"]                 = { name = "Treetop",              icon = "󰯂 ", hl = 7 },
	["trustees"]                = { name = "Trustees",             icon = "󰯂 ", hl = 7 },
	["tsalt"]                   = { name = "Telix SALT",           icon = "󰯂 ", hl = 7 },
	["tsscl"]                   = { name = "TSS Command",          icon = "󰯂 ", hl = 7 },
	["tssgm"]                   = { name = "TSS Geometry",         icon = "󰯂 ", hl = 7 },
	["tssop"]                   = { name = "TSS Optics",           icon = "󰯂 ", hl = 7 },
	["tt3"]                     = { name = "TT3",                  icon = "󰯂 ", hl = 7 },
	["tt3html"]                 = { name = "HTML+TT3",             icon = " ", hl = 1 },
	["tt3js"]                   = { name = "Javascript+TT3",       icon = " ", hl = 1 },
	["ts"]                      = { name = "Typescript",           icon = " ", hl = 4 },
	["typescript"]              = { name = "Typescript",           icon = " ", hl = 4 },
	["typescriptreact"]         = { name = "React",                icon = " ", hl = 4 },
	["typ"]                     = { name = "Typst",                icon = " ", hl = 7 },
	["uc"]                      = { name = "UnrealScript",         icon = " ", hl = 1 },
	["uci"]                     = { name = "OpenWrt Config",       icon = " ", hl = 4 },
	["udevconf"]                = { name = "Udev Config",          icon = " ", hl = 4 },
	["udevperm"]                = { name = "Udev Permissions",     icon = "󰯂 ", hl = 7 },
	["udevrules"]               = { name = "Udev rules",           icon = "󰯂 ", hl = 7 },
	["uil"]                     = { name = "Motif UIL",            icon = "󰯂 ", hl = 7 },
	["unison"]                  = { name = "Unison",               icon = "󰯂 ", hl = 7 },
	["updatedb"]                = { name = "updatedb.conf Config", icon = " ", hl = 4 },
	["upstart"]                 = { name = "Upstart job",          icon = "󰯂 ", hl = 7 },
	["vb"]                      = { name = "Visual Basic",         icon = "󰯂 ", hl = 7 },
	["vera"]                    = { name = "Vera",                 icon = "󰯂 ", hl = 7 },
	["verilog"]                 = { name = "Verilog",              icon = "󰯂 ", hl = 7 },
	["verilogams"]              = { name = "Verilog-AMS",          icon = "󰯂 ", hl = 7 },
	["vgrindefs"]               = { name = "Vgrindefs",            icon = "󰯂 ", hl = 7 },
	["vhdl"]                    = { name = "VHDL",                 icon = "󰯂 ", hl = 7 },
	["vim"]                     = { name = "Vim",                  icon = " ", hl = 5 },
	["viminfo"]                 = { name = "Viminfo",              icon = " ", hl = 1 },
	["virata"]                  = { name = "Virata AConfig",       icon = " ", hl = 4 },
	["vmasm"]                   = { name = "(VAX) Macro Assembly", icon = " ", hl = 7 },
	["voscm"]                   = { name = "VOS CM macro",         icon = "󰯂 ", hl = 7 },
	["vrml"]                    = { name = "VRML97",               icon = "󰯂 ", hl = 7 },
	["vsejcl"]                  = { name = "JCL",                  icon = "󰯂 ", hl = 7 },
	["vue"]                     = { name = "Vue",                  icon = " ", hl = 5 },
	["wat"]                     = { name = "WebAssembly",          icon = " ", hl = 6 },
	["wdiff"]                   = { name = "wDiff",                icon = "󰕚 ", hl = 3 },
	["wdl"]                     = { name = "wdl",                  icon = "󰯂 ", hl = 7 },
	["web"]                     = { name = "WEB",                  icon = "󰖟 ", hl = 6 },
	["webmacro"]                = { name = "WebMacro",             icon = "󰯂 ", hl = 7 },
	["wget"]                    = { name = "Wget Config",          icon = " ", hl = 4 },
	["wget3"]                   = { name = "Wget3 Config",         icon = " ", hl = 4 },
	["wml"]                     = { name = "WML",                  icon = "󰯂 ", hl = 7 },
	["wsml"]                    = { name = "WSML",                 icon = "󰯂 ", hl = 7 },
	["wvdial"]                  = { name = "WvDial Config",        icon = " ", hl = 4 },
	["xbl"]                     = { name = "XBL",                  icon = "󰯂 ", hl = 7 },
	["xcompose"]                = { name = "XCompose",             icon = "󰯂 ", hl = 7 },
	["xf87conf"]                = { name = "XF87Config",           icon = "󰯂 ", hl = 7 },
	["xhtml"]                   = { name = "XHTML",                icon = "󰯂 ", hl = 7 },
	["xinetd"]                  = { name = "xinetd.conf Config",   icon = " ", hl = 4 },
	["xkb"]                     = { name = "XKB",                  icon = "󰯂 ", hl = 7 },
	["xmath"]                   = { name = "XMath",                icon = "󰯂 ", hl = 7 },
	["xml"]                     = { name = "XML",                  icon = "󰗀 ", hl = 7 },
	["xmodmap"]                 = { name = "Xmodmap Definition",   icon = "󰯂 ", hl = 7 },
	["xpm"]                     = { name = "X Pixmap",             icon = "󰯂 ", hl = 7 },
	["xpm3"]                    = { name = "X Pixmap v3",          icon = "󰯂 ", hl = 7 },
	["xquery"]                  = { name = "XQuery",               icon = "󰯂 ", hl = 7 },
	["xs"]                      = { name = "XS",                   icon = "󰯂 ", hl = 7 },
	["xsd"]                     = { name = "XSD",                  icon = "󰯂 ", hl = 7 },
	["xslt"]                    = { name = "XSLT",                 icon = "󰯂 ", hl = 7 },
	["xxd"]                     = { name = "XXD",                  icon = "󰯂 ", hl = 7 },
	["yacc"]                    = { name = "Yacc",                 icon = "󰯂 ", hl = 7 },
	["yaml"]                    = { name = "YAML",                 icon = "󰯂 ", hl = 4 },
	["z8a"]                     = { name = "asz81",                icon = " ", hl = 7 },
	["zathurarc"]               = { name = "Zathurarc",            icon = "󰯂 ", hl = 7 },
	["zig"]                     = { name = "Zig",                  icon = " ", hl = 4 },
	["zimbu"]                   = { name = "Zimbu",                icon = "󰯂 ", hl = 7 },
	["zir"]                     = { name = "Zir",                  icon = "󰯂 ", hl = 7 },
	["zserio"]                  = { name = "Zserio",               icon = "󰯂 ", hl = 7 },
	["zsh"]                     = { name = "Zsh",                  icon = " ", hl = 5 }
	---_
};

filetypes.overwrite = function (config)
	if type(config) ~= "table" then
		return;
	end

	for k, v in pairs(config) do
		filetypes.entries[k] = vim.tbl_extend("force", filetypes.entries[k] or {}, v);
	end
end

--- Gets Icons
---@param ft string?
---@return { name: string, icon: string, hl: integer }
filetypes.get = function (ft)
	local _ft = ft;

	if vim.filetype.match({ filename = string.format("example.%s", _ft) }) then
		_ft = vim.filetype.match({ filename = string.format("example.%s", _ft) });
	end

	local conf = {};

	conf = filetypes.entries[_ft] or filetypes.entries[ft] or filetypes.entries["default"];

	local this_conf = filetypes.entries[_ft] or filetypes.entries[ft] or filetypes.entries.default;
	conf.name = this_conf.name or ft or "Unknown";

	return conf;
end

return filetypes;
